"""empty message

Revision ID: 2f8fb6d79824
Revises: aead1ca0a9e3
Create Date: 2020-06-05 16:31:15.677947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f8fb6d79824'
down_revision = 'aead1ca0a9e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('life_users', 'birth_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('life_users', 'state',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=65),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('life_users', 'state',
               existing_type=sa.String(length=65),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('life_users', 'birth_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
