"""city column added in blood_bank_model

Revision ID: 90fbbdb9bcb0
Revises: f21f29a7d65e
Create Date: 2020-03-23 10:46:28.296914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fbbdb9bcb0'
down_revision = 'f21f29a7d65e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blood_banks', sa.Column('city', sa.String(length=65), nullable=False))
    op.create_index(op.f('ix_blood_banks_city'), 'blood_banks', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blood_banks_city'), table_name='blood_banks')
    op.drop_column('blood_banks', 'city')
    # ### end Alembic commands ###
