"""city added and datatype changed

Revision ID: aead1ca0a9e3
Revises: 
Create Date: 2020-06-05 16:28:34.722594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aead1ca0a9e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('life_users', sa.Column('city', sa.String(length=65), nullable=False))
    op.create_index(op.f('ix_life_users_city'), 'life_users', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_life_users_city'), table_name='life_users')
    op.drop_column('life_users', 'city')
    # ### end Alembic commands ###
