"""columns added in blood bank model

Revision ID: d7c288b54a1d
Revises: bc9f9dde1339
Create Date: 2020-04-08 09:43:21.231459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c288b54a1d'
down_revision = 'bc9f9dde1339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blood_banks', sa.Column('contact_number', sa.BigInteger(), nullable=True))
    op.add_column('blood_banks', sa.Column('district', sa.String(length=65), nullable=True))
    op.add_column('blood_banks', sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('blood_banks', sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True))
    op.add_column('blood_banks', sa.Column('mobile_number', sa.BigInteger(), nullable=True))
    op.add_column('blood_banks', sa.Column('pincode', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_blood_banks_district'), 'blood_banks', ['district'], unique=False)
    op.create_index(op.f('ix_blood_banks_latitude'), 'blood_banks', ['latitude'], unique=False)
    op.create_index(op.f('ix_blood_banks_longitude'), 'blood_banks', ['longitude'], unique=False)
    op.create_index(op.f('ix_blood_banks_pincode'), 'blood_banks', ['pincode'], unique=False)
    op.drop_index('email', table_name='blood_banks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'blood_banks', ['email'], unique=True)
    op.drop_index(op.f('ix_blood_banks_pincode'), table_name='blood_banks')
    op.drop_index(op.f('ix_blood_banks_longitude'), table_name='blood_banks')
    op.drop_index(op.f('ix_blood_banks_latitude'), table_name='blood_banks')
    op.drop_index(op.f('ix_blood_banks_district'), table_name='blood_banks')
    op.drop_column('blood_banks', 'pincode')
    op.drop_column('blood_banks', 'mobile_number')
    op.drop_column('blood_banks', 'longitude')
    op.drop_column('blood_banks', 'latitude')
    op.drop_column('blood_banks', 'district')
    op.drop_column('blood_banks', 'contact_number')
    # ### end Alembic commands ###
