"""empty message

Revision ID: dd9d97f581a0
Revises: 90fbbdb9bcb0
Create Date: 2020-03-27 14:57:54.894712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd9d97f581a0'
down_revision = '90fbbdb9bcb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blood_banks_city', table_name='blood_banks')
    op.drop_column('blood_banks', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blood_banks', sa.Column('city', mysql.VARCHAR(length=65), nullable=False))
    op.create_index('ix_blood_banks_city', 'blood_banks', ['city'], unique=False)
    # ### end Alembic commands ###
